#! /usr/bin/env perl
#
# Andrew Janke - a.janke@gmail.com
# Center for Magnetic Resonancse
# The University of Queensland
#
# Copyright Andrew Janke, The University of Queensland.
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted,
# provided that the above copyright notice appear in all copies.  The
# author and the University of Queensland make no representations about the
# suitability of this software for any purpose.  It is provided "as is"
# without express or implied warranty.

my($avig_xfm, $avg_xfm_inv);
      my @xfms = glob "reg*";
      # set up file names
      $avg_xfm = "average-xfm.xfm";
      $avg_xfm_inv = "average-xfm.inv.xfm";
      
      # first get the average xfm
      &do_cmd('xfmavg', '-clobber', @xfms, $avg_xfm);
      
      # then invert it
      &do_cmd('xfminvert', $avg_xfm, $avg_xfm_inv);
      
sub do_cmd {
   print STDOUT "@_\n"; #if $opt{'verbose'};
   system(@_) == 0 or die "\n: Failed executing @_\n\n";
   }
      
