#! /usr/bin/env perl
#
# Andrew Janke - a.janke@gmail.com
# Center for Magnetic Resonancse
# The University of Queensland
#
# Copyright Andrew Janke, The University of Queensland.
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted,
# provided that the above copyright notice appear in all copies.  The
# author and the University of Queensland make no representations about the
# suitability of this software for any purpose.  It is provided "as is"
# without express or implied warranty.

#print STDOUT "| [$iter_txt] $_\n" if !$opt{'quiet'};
my($filename, $target, $current_xfm, $fit_args);
$filename = $ARGV[0];
$target = $ARGV[1];
$fit_args = $ARGV[2];   
      # xfm filename
      $current_xfm= "reg.xfm";
      
      # create transformation
      &do_cmd('minctracc', '-clobber',
              split(/\ /, $fit_args),
              $filename, $target, $current_xfm );

sub do_cmd {
   print STDOUT "@_\n"; #if $opt{'verbose'};
   system(@_) == 0 or die "\n: Failed executing @_\n\n";
   }
