#! /usr/bin/env perl
#
# Andrew Janke - a.janke@gmail.com
# Center for Magnetic Resonancse
# The University of Queensland
#
# Copyright Andrew Janke, The University of Queensland.
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted,
# provided that the above copyright notice appear in all copies.  The
# author and the University of Queensland make no representations about the
# suitability of this software for any purpose.  It is provided "as is"
# without express or implied warranty.

# generate the new xfms

my ($infile, $avg_xfm_inv);
         # set up new filename
         $infile = $ARGV[0];
	 $avg_xfm_inv = $ARGV[1];
         $outfile = "reg.avg.xfm";
         
         # concatenate the original + inverse of the average
         &do_cmd('xfmconcat', $infile, $avg_xfm_inv, $outfile);
      

sub do_cmd {
   print STDOUT "@_\n"; #if $opt{'verbose'};
   system(@_) == 0 or die "\n: Failed executing @_\n\n";
   }
